/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltp4j_SplitSentence */

#ifndef _Included_edu_hit_ir_ltp4j_SplitSentence
#define _Included_edu_hit_ir_ltp4j_SplitSentence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltp4j_SplitSentence
 * Method:    splitSentence
 * Signature: (Ljava/lang/String;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltp4j_SplitSentence_splitSentence
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
