/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltp4j_Ner */

#ifndef _Included_edu_hit_ir_ltp4j_Ner
#define _Included_edu_hit_ir_ltp4j_Ner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltp4j_Ner
 * Method:    create
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_Ner_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_hit_ir_ltp4j_Ner
 * Method:    recognize
 * Signature: (Ljava/util/List;Ljava/util/List;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_Ner_recognize
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     edu_hit_ir_ltp4j_Ner
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltp4j_Ner_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
