/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltp4j_Srl */

#ifndef _Included_edu_hit_ir_ltp4j_Srl
#define _Included_edu_hit_ir_ltp4j_Srl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltp4j_Srl
 * Method:    create
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_Srl_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_hit_ir_ltp4j_Srl
 * Method:    srl
 * Signature: (Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_Srl_srl
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     edu_hit_ir_ltp4j_Srl
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltp4j_Srl_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
