/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltp4j_Postag */

#ifndef _Included_edu_hit_ir_ltp4j_Postag
#define _Included_edu_hit_ir_ltp4j_Postag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltp4j_Postag
 * Method:    create
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_Postag_create__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_hit_ir_ltp4j_Postag
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_Postag_create__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     edu_hit_ir_ltp4j_Postag
 * Method:    postag
 * Signature: (Ljava/util/List;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_Postag_postag
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     edu_hit_ir_ltp4j_Postag
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltp4j_Postag_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
